server:
  port: 8016
  servlet:
    context-path: /flow-server

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    check-template-location: true
    mode: HTML5
    prefix: classpath:/templates
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
security:
  oauth2:
    client:
      client-id: flow-app
      client-secret: 123456
      user-authorization-uri: http://auth.fan.com:8011/oauth/authorize
      access-token-uri: http://auth.fan.com:8011/oauth/token
    resource:
      token-info-uri: http://auth.fan.com:8011/oauth/check_token

logging:
  level:
    root: info
