server:
  port: 8010
  servlet:
    context-path: /api-server

spring:
  redis:
    database: 0
    host: 192.168.205.150
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000

auth:
  security:
    type: token
    authServer: http://auth.fan.com:8011/oauth/authorize
    tokenServer: http://auth.fan.com:8011/oauth/token
    client:
      id: api-app
      secret: 123456
      callback: http://web.fan.com:8010/api-server/oauth/callback
      state: http://vue.fxl.com:8080/